# Generated by Django 5.2.7 on 2025-10-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='homepage_screenshot',
            field=models.ImageField(blank=True, help_text='Homepage preview thumbnail (recommended: 400x300px)', null=True, upload_to='tenant_screenshots/'),
        ),
    ]
