# Generated by Django 5.2.7 on 2025-10-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteproject',
            name='business_address_line1',
            field=models.CharField(blank=True, help_text='Street address', max_length=255),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='business_address_line2',
            field=models.CharField(blank=True, help_text='Apartment, suite, etc. (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='business_city',
            field=models.CharField(blank=True, help_text='City', max_length=100),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='business_country',
            field=models.CharField(blank=True, default='United States', help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='business_postal_code',
            field=models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='business_state',
            field=models.CharField(blank=True, help_text='State/Province', max_length=100),
        ),
    ]
